<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDC8-DX-6MWHH92" ignored="0" name="Test2" tests="1" failures="1" timestamp="18 Jul 2018 05:09:02 GMT" time="21.194" errors="0">
  <testcase name="testLogin" time="21.162" classname="training.Newclass">
    <failure type="java.lang.AssertionError" message="expected [Sign in to GitHub · GitHub] but found [GitHub]">
      <![CDATA[java.lang.AssertionError: expected [Sign in to GitHub · GitHub] but found [GitHub]
at training.Newclass.testLogin(Newclass.java:40)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
</testsuite> <!-- Test2 -->
